Add remaining steps for blue-green

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -44,12 +44,30 @@ jobs:
             - run:
                 name: Deploy to EBS
                 command: |
-                    echo 'export VERSION=$(date "+%d-%m-%y_%H-%M-%S")' >> $BASH_ENV
+#                    Get current version of latest env from ebs
+                    all_versions=$(aws elasticbeanstalk describe-application-versions --profile deployer)
+                    current_version=$(echo $all_versions | jq '.ApplicationVersions[0].VersionLabel')
+
+#                    Increment version number by 1 and export to $BASH_ENV
+                    echo "export VERSION=$(($current_version + 1))" >> $BASH_ENV
                     source $BASH_ENV
+
+#                    Zip project files excluding vendor and copy to ebs S3 bucket
                     zip ./sourcebundle.zip -r * .[^.]* -x "vendor/*"
                     aws s3 cp sourcebundle.zip s3://elasticbeanstalk-eu-west-2-444397649125/sourcebundle.zip --profile deployer
+
+#                    Create new version of App using zip in S3
                     aws elasticbeanstalk create-application-version --application-name blue-green-deployments --version-label $VERSION --source-bundle S3Bucket="elasticbeanstalk-eu-west-2-444397649125",S3Key="sourcebundle.zip" --auto-create-application --profile deployer
-                    aws elasticbeanstalk update-environment --application-name blue-green-deployments --environment-name BlueGreenDeployments-blue --version-label $VERSION --solution-stack-name "64bit Amazon Linux 2018.03 v2.8.15 running PHP 7.2" --profile deployer
+
+#                    Update either green or blue environment of app based on which is oldest
+                    aws elasticbeanstalk update-environment --application-name blue-green-deployments --environment-name $env_to_update --version-label $VERSION --solution-stack-name "64bit Amazon Linux 2018.03 v2.8.15 running PHP 7.2" --profile deployer
+
+#                   Swap CNAMES
+                    source_env_name=$(aws elasticbeanstalk describe-environments --profile learning | jq '.Environments | sort_by(.DateUpdated)[0].EnvironmentName')
+                    destination_env_name=$([ "$env_to_update" = "BlueGreenDeployments-blue" ] && echo "BlueGreenDeployments-green" || echo "BlueGreenDeployments-blue")
+                    aws elastibeanstalk swap-environment-cnames --source-environment-name source_env_name --destination-environment-name destination_env_name
+
+#                    Cleanup
                     rm -rf ./sourcebundle.zip
 
 workflows:
